name: starter_app
description: "App to control video robot"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  responsive_builder: ^0.7.1
  get_it: ^7.7.0
  provider: ^6.1.2
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.1
  page_transition: ^2.1.0
  json_annotation: ^4.9.0
  flutter_downloader: ^1.11.8
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.4.0
  badges: ^3.1.2
  video_player: ^2.9.1
  webview_flutter: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true

  assets:
     - .env
     - assets/

